kind: BuildConfig
apiVersion: v1
metadata:
  name: api-gateway-pipeline
spec:
  type: JenkinsPipeline
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'api-gateway', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'api-gateway')
        }
